name: mc_project
description: "A new Flutter project."

publish_to: 'none'  #remove this line to publish on pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  firebase_core: ^3.7.0
  cloud_firestore: ^5.4.5
  get: ^4.6.6
  dropdown_button2: ^2.3.9
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
